### PR TITLE
partially applied primitive types

### LINKED ISSUE #190: kind-inference bug with primitive type constructors
Using `IO`, `List`, or `Maybe` at kind `* -> *` results in a kind error: 

```
#lang "prelude.kl"
(import "list.kl")

(datatype (OfUnit F)
  (of-unit
    (F Unit)))


-- of-unit-io : (OfUnit IO)
(define of-unit-io
  (of-unit (pure-IO unit)))

-- Kind mismatch at IO: * ≠ (* → *)
(example
  (the (OfUnit IO)
       of-unit-io))


-- of-unit-list : (OfUnit List)
(define of-unit-list
  (of-unit (list unit)))
(example of-unit-list)

-- Kind mismatch at List: * ≠ (* → *)
(example
  (the (OfUnit List)
       of-unit-list))


-- of-unit-maybe : (OfUnit Maybe)
(define of-unit-maybe
  (of-unit (just unit)))
(example of-unit-maybe)

-- Kind mismatch at Maybe: * ≠ (* → *)
(example
  (the (OfUnit (Maybe))
       of-unit-maybe))


-- works fine with non-primitive datatypes
(datatype (MyMaybe A)
  (my-nothing)
  (my-just A))

-- of-unit-my-maybe : (OfUnit (MyMaybe))
(define of-unit-my-maybe
  (of-unit (my-just unit)))
(example of-unit-my-maybe)

(example
  (the (OfUnit (MyMaybe))
       of-unit-my-maybe))
```

### PR DESCRIPTION
**Pull request by gelisam**
Fixes #190

### CODE REVIEW

File: src/Expander.hs [hunk 1]
```diff
@@ -688,22 +688,24 @@ initializeKernel outputChannel = do
...
-                 then throwError $ WrongDatatypeArity stx dt
-                                     (fromIntegral $ length argKinds)
-                                     (length args)
-                 else do
-                   argDests <- traverse (uncurry scheduleType) (zip argKinds args)
-                   linkType dest $ tDatatype dt argDests
+            \k dest stx -> do
+              Stx _ _ (me, args) <- mustBeCons stx
+              _ <- mustBeIdent me
+              if length args > length argKinds
```
Comment (gelisam) [inline src/Expander.hs:694]: Now accepting the case in which fewer arguments are provided than required, e.g. `(Either (Unit))` instead of `(Either (Unit) (Unit))`.

File: src/Expander.hs [hunk 2]
```diff
@@ -688,22 +688,24 @@ initializeKernel outputChannel = do
...
+                then throwError $ WrongDatatypeArity stx dt
+                                    (fromIntegral $ length argKinds)
+                                    (length args)
+                else do
+                  let missingArgs :: [Kind]
+                      missingArgs = drop (length args) argKinds
+                  equateKinds stx (kFun missingArgs KStar) k
+                  argDests <- traverse (uncurry scheduleType) (zip argKinds args)
```
Comment (gelisam) [inline src/Expander.hs:702]: The `zip` now drops the last few entries in `argKinds`, those for which the user did not provide a type argument. Those dropped entries are now in `missingArgs`.

File: src/Expander/Error.hs [hunk 3]
```diff
@@ -34,7 +34,7 @@ data ExpansionErr
   | NotInteger Syntax
   | NotString Syntax
   | NotModName Syntax
-  | NotRightLength Natural Syntax
+  | NotRightLength [Natural] Syntax
```
Comment (gelisam) [inline src/Expander/Error.hs:37]: Generalizing the "expected a list of length 3" message to "expected a list of length 1, 2, or 3".

File: src/Expander/Primitives.hs [hunk 4]
```diff
@@ -406,7 +406,7 @@ listSyntax :: ExprPrim
 listSyntax t dest stx = do
   unify dest t tSyntax
   Stx _ _ (_, list, source) <- mustHaveEntries stx
-  Stx _ _ listItems <- mustHaveEntries list
+  listItems <- mustHaveShape list
```
Comment (gelisam) [inline src/Expander/Primitives.hs:409]: This was the only place where we were using `mustHaveEntries` to assert that a Syntax is a List. I have dropped support for this feature, add is it already supported by `mustHaveShape`.

`mustHaveEnteies` now only supports checking that it is a List with a required number of elements, but I have generalized `mustHaveEntries` so that this required number can be "Either N or M" and not just a single number N.

File: src/Expander/Primitives.hs [hunk 5]
```diff
@@ -486,7 +486,7 @@ log t dest stx = do
 whichProblem :: ExprPrim
 whichProblem t dest stx = do
   unify dest (tMacro (primitiveDatatype "Problem" [])) t
-  Stx _ _ (_ :: Syntax) <- mustHaveEntries stx
+  Stx _ _ (Identity _) <- mustHaveEntries stx
```
Comment (gelisam) [inline src/Expander/Primitives.hs:489]: I have changed the `mustHaveEntries` API so that a singleton tuple is now represented via an `Identity` wrapper and not just by the element itself. One nice consequence of that is that a type annotation is no longer needed in order to drive the type class resolution algorithm.

File: src/Expander/Syntax.hs [hunk 6]
```diff
@@ -59,38 +64,72 @@ mustBeModName (Syntax (Stx scs srcloc (Id "kernel"))) =
...
+      throwError (NotRightLength lengths stx)
+mustHaveEntries other = do
+  throwError (NotList other)
+
+class FixedLengthList item r where
+  checkLength :: [item] -> Either [Natural] r
+
+instance ( FixedLengthList e1 a
+         , FixedLengthList e2 b
+         , e1 ~ e2
```
Comment (gelisam) [inline src/Expander/Syntax.hs:86]: hmm, I don't think that's right, I don't need to use two different type variables `e1` and `e2` here.

File: src/Expander.hs (hunk 1 above)
Comment (david-christiansen) [reply src/Expander.hs:694]: Why is it that these types explicitly need to check for too many arguments? Wouldn't the kind system figure that part out? (Basically, isn't `WrongDatatypeArity` a thing made obsolete by the introduction of kinds other than `*`?)

File: src/Expander.hs (hunk 2 above)
Comment (david-christiansen) [reply src/Expander.hs:702]: Nice!

File: src/Expander/Primitives.hs (hunk 4 above)
Comment (david-christiansen) [reply src/Expander/Primitives.hs:409]: This seems like a nice change.

File: src/Expander/Primitives.hs (hunk 5 above)
Comment (david-christiansen) [reply src/Expander/Primitives.hs:489]: Sounds reasonable!

File: stdlib/n-ary-app.kl [hunk 7]
```diff
@@ -105,10 +105,17 @@
                     [(list (arg1 arg2))
                      (pure (list-syntax ('-> arg1 arg2)
                                         stx))]
+                    [(list (arg1))
+                     (pure (list-syntax ('-> arg1)
+                                        stx))]
```
Comment (gelisam) [inline stdlib/n-ary-app.kl:110]: The kernel now supports 0, 1, or 2 arguments (`(->)`, `(-> A)`, or `(-> A B)`). The prelude's n-ary wrapper was only supporting 2 or more arguments. This extends the wrapper to also support 1 argument.

File: src/Expander/Primitives.hs [hunk 8]
```diff
@@ -529,41 +529,73 @@ arrowType :: TypePrim
...
 macroType :: TypePrim
-macroType = unaryType (\a -> tMacro a)
+macroType = unaryType TMacro
 
 ioType :: TypePrim
-ioType = unaryType tIO
+ioType = unaryType TIO
 
-unaryType :: (forall a . a -> TyF a) -> TypePrim
+unaryType :: TypeConstructor -> TypePrim
```
Comment (david-christiansen) [inline src/Expander/Primitives.hs:573]: This is exactly what we'd expect it to have with proper kinds. But I wonder whether we should have `unaryType` instead of something like `typeConstructor :: TypeConstructor -> Kind -> TypePrim`. This would move some errors from being syntax errors to being kind errors, but that seems reasonable enough to me. Am I missing something?

File: stdlib/n-ary-app.kl [hunk 9]
```diff
@@ -105,10 +105,17 @@
...
                     [(cons arg1 args)
                      (pure (list-syntax ('-> arg1
                                           (cons-list-syntax 'my-arrow args stx))
-                                        stx))])]))]))
+                                        stx))]
+                    [()
+                     (pure '(->))])]
+                 [_
+                  (pure '(->))]))]))
```
Comment (gelisam) [inline stdlib/n-ary-app.kl:118]: This extends the wrapper to support a syntax which the kernel does not support, namely `->` without parentheses. Hmm, I should probably change `higher-kinded.kl` to test both `->` and `(->)`...

File: src/Expander.hs (hunk 1 above)
Comment (gelisam) [reply src/Expander.hs:694]: Oh nice, I didn't realize that check was no longer necessary!

File: src/Expander/Primitives.hs (hunk 8 above)
Comment (david-christiansen) [reply src/Expander/Primitives.hs:573]: Then the same implementation could be used for declared datatypes as for builtins like IO, increasing the robustness of the system.

File: examples/higher-kinded.golden [hunk 10]
```diff
@@ -0,0 +1,6 @@
+(of-unit #<IO action>) : (OfUnit IO)
+(of-unit #<closure>) : (OfUnit ((→) Unit))
```
Comment (david-christiansen) [inline examples/higher-kinded.golden:2]: Is this a bug in the type pretty printer? I'd expect it to say `(OfUnit (→ Unit))` here.

File: src/Expander.hs (hunk 1 above)
Comment (david-christiansen) [reply src/Expander.hs:694]: Well, it's only no longer necessary if there's not a missing check in the kind checker :-) It's worth testing that case if it's not already there.

File: src/Expander/Primitives.hs (hunk 8 above)
Comment (gelisam) [reply src/Expander/Primitives.hs:573]: Unifying our series of specialized `plainType`, `unaryType` and `binaryType` functions into a single `typeConstructor` function does seem like a good idea, thanks!

File: examples/higher-kinded.golden (hunk 10 above)
Comment (gelisam) [reply examples/higher-kinded.golden:2]: In core, the type `(-> A B C)` is printed as `A → (B → C)`, so I think other occurrences of `→` are intentionally printed as `(→)` in order to make sure `Monad (→) Unit` doesn't accidentally get printed as `Monad → Unit`, as that would be confusing.

When `→` has arguments, though, I agree it makes sense to print those arguments inside the parens.

Comment (gelisam) [reply examples/higher-kinded.golden:2]: Thinking about this more, it's only the cases in which `→` has zero or one arguments which are a special case:

```
(→)
(→ A)
A → B
A → (B → C)
```

The current code accounts for the zero case, but not the one case.

File: src/Expander.hs (hunk 1 above)
Comment (gelisam) [reply src/Expander.hs:694]: Alas, without this `if length args > length argKinds` check, the following is accepted. I have just created #194 to track this.

```
-- (just unit) : (Maybe Unit) 
(example
  (the (Maybe Unit Unit)
       (just unit)))
```

Comment (gelisam) [reply src/Expander.hs:694]: What about the similar check a few lines below, for type patterns? A value of type `Type` could hold a type of a kind other than `*` (as demonstrated by the variable named `type` in this PR's `higher-kinded-patterns.kl` example, which holds a type of kind `* -> *`), so the kind checker doesn't have much information with which to perform its check.

File: src/Expander/Syntax.hs (hunk 6 above)
Comment (gelisam) [reply src/Expander/Syntax.hs:86]: Fixed in 2ca2a30a4a731068974fb7c21f75d424b0a69bea, and this change also removes the need for `UndecidableInstances` in this file.

File: stdlib/n-ary-app.kl (hunk 9 above)
Comment (gelisam) [reply stdlib/n-ary-app.kl:118]: Tested in 2847b4e3f2072c9f6c7d24c50bcf3fe8d2fd3812.

File: examples/higher-kinded.golden (hunk 10 above)
Comment (gelisam) [reply examples/higher-kinded.golden:2]: Fixed in e02824619e25f08ba2a2433ae38f185671218a84.

File: src/Expander/Primitives.hs (hunk 8 above)
Comment (gelisam) [reply src/Expander/Primitives.hs:573]: That one is a bit more involved, I'll do it in a separate PR

Comment (gelisam) [reply src/Expander/Primitives.hs:573]: Created #195 to track this, so I don't forget

File: src/Expander.hs (hunk 1 above)
Comment (david-christiansen) [reply src/Expander.hs:694]: It seems plausible to me that type patterns should be well-kinded, and that this should be caught. What I'm less sure of is whether they should all have kind *, or whether it makes sense to match against other types during expansion.

File: src/Expander/Syntax.hs (hunk 6 above)
Comment (david-christiansen) [reply src/Expander/Syntax.hs]: :confetti_ball:

File: examples/higher-kinded.golden (hunk 10 above)
Comment (david-christiansen) [reply examples/higher-kinded.golden]: Nice

**Review by david-christiansen — APPROVED** [review]

File: src/Expander.hs (hunk 1 above)
Comment (gelisam) [reply src/Expander.hs:694]: I have created #196 to continue the discussion on type patterns after I merge this PR.
